estudiantes/urls.py
from django.urls import path
from . import views  # Importa el módulo views
from django.contrib.auth import views as auth_views
from .views import *


urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.LoginPage, name="login"),  # login
    path('home/', views.HomePage, name="home"),  # home
    
    path('logout/', views.LogoutPage, name='logout'),  # SALIR
    path('ingreso/', views.ingreso, name='ingreso'),  # ingreso
    path('registro/', views.registro, name='registro'),  # registro
    path('manage-users/', views.manage_users, name='manage_users'),
    
    path('test/', views.test, name='test'),
    path('varios/', views.varios, name='varios'),
    
    path('aprobar_usuario/<int:pk>/', views.aprobar_usuario, name='aprobar_usuario'),
    path('rechazar_estudiante/<int:pk>/', views.rechazar_estudiante, name='rechazar_estudiante'),
    
    path('aprobar_carta/<int:pk>/', views.aprobar_carta, name='aprobar_carta'),
    path('rechazar_carta/<int:pk>/', views.rechazar_carta, name='rechazar_carta'),
    path('enviar_carta_aprobacion/', views.enviar_carta_aprobacion, name='enviar_carta_aprobacion'),
    path('ver_carta/<int:pk>/', views.ver_carta, name='ver_carta'),
    
    
    path('empresa/', views.EmpresaListView.as_view(), name='empresa_list'),  # Ahora importa la clase desde views.py
    path('empresa/<int:pk>/', views.EmpresaDetailView.as_view(), name='empresa_detail'),
    path('empresa/create/', views.EmpresaCreateView.as_view(), name='empresa_create'),
    path('empresa/<int:pk>/update/', views.EmpresaUpdateView.as_view(), name='empresa_update'),
    path('empresa/<int:pk>/delete/', views.EmpresaDeleteView.as_view(), name='empresa_delete'),
    path('empresa_eliminar/<int:pk>', views.empresa_eliminar, name='empresa_eliminar'),
    
    path('escoger_empresa/<int:pk>/', views.escoger_empresa, name='escoger_empresa'),
    path('escogiendo_empresa/', views.escogiendo_empresa, name='escogiendo_empresa'),
    
    path('empresas/', views.empresas, name='empresas'),
    path('empresa_asignado/', views.empresa_asignado, name='empresa_asignado'),
    path('empresas_estudiante/<int:pk>/', views.empresas_estudiante, name='empresas_estudiante'), 
    
    path('rol/', views.RolListView.as_view(), name='rol_list'),
    path('rol/<int:pk>/', views.RolDetailView.as_view(), name='rol_detail'),
    path('rol/create/', views.RolCreateView.as_view(), name='rol_create'),
    path('rol/<int:pk>/update/', views.RolUpdateView.as_view(), name='rol_update'),
    path('rol/<int:pk>/delete/', views.RolDeleteView.as_view(), name='rol_delete'),
    
    path('formato/', views.FormatoListView.as_view(), name='formato_list'),
    path('formato/<int:pk>/', views.FormatoDetailView.as_view(), name='formato_detail'),
    path('formato/create/', views.FormatoCreateView.as_view(), name='formato_create'),
    path('formato/<int:pk>/update/', views.FormatoUpdateView.as_view(), name='formato_update'),
    path('formato/<int:pk>/delete/', views.FormatoDeleteView.as_view(), name='formato_delete'),
    
    path('tutores/', views.tutor_list, name='tutor_list'),
    path('tutores/<int:pk>/', views.tutor_detail, name='tutor_detail'),
    path('tutores/nuevo/', views.tutor_create, name='tutor_create'),
    path('tutores/<int:pk>/editar/', views.tutor_update, name='tutor_update'),
    path('tutores/<int:pk>/eliminar/', views.tutor_delete, name='tutor_delete'),
    
    path('tutor_asignar/<int:pk>/', views.tutor_asignar, name='tutor_asignar'),
    path('tutor_asignado/', views.tutor_asignado, name='tutor_asignado'),
    path('tutor/', views.tutor, name='tutor'),
    path('tutor_documentos/', views.tutor_documentos, name='tutor_documentos'),
    path('tutor_estudiantes/', views.tutor_estudiantes, name='tutor_estudiantes'),
    path('tutor_actualizar/', views.tutor_actualizar, name='tutor_actualizar'),
    
    path('visita_lista/', views.visita_lista, name='visita_lista'),
    path('visita_academica/<int:pk>/', views.visita_academica, name='visita_academica'),
    path('ver_visita/<str:estudiante>/<int:numero_visita>/', views.ver_visita, name='ver_visita'),
    
    path('evaluacion_actividades_tutor/', views.evaluacion_actividades_tutor, name='evaluacion_actividades_tutor'),
    path('evaluacion_actividades/<int:pk>/', views.evaluacion_actividades, name='evaluacion_actividades'),
    path('evaluacion_lista/', views.evaluacion_lista, name='evaluacion_lista'),
    path('ver_evaluacion/<int:pk>/', views.ver_evaluacion, name='ver_evaluacion'),
    path('aprobar_evaluacion/<int:pk>/', views.aprobar_evaluacion, name='aprobar_evaluacion'),
    
    path('registro_semanal/', views.registro_semanal, name='registro_semanal'),
    path('registro_semanal_lista/', views.registro_semanal_lista, name='registro_semanal_lista'),
    path('registro_semanal_ver/<int:pk>/', views.registro_semanal_ver, name='registro_semanal_ver'),
    path('registro_semanal_eliminar/<int:pk>/', views.registro_semanal_eliminar, name='registro_semanal_eliminar'),
    
    path('formulario_ia/', views.formulario_ia, name='formulario_ia'),
    path('analisis_ia/', views.analisis_ia, name='analisis_ia'),
    
    path('cambiar-contrasena/', CustomPasswordChangeView, name='password_change'),
    path('cambiar-contrasena-exito/', auth_views.PasswordChangeDoneView.as_view(template_name='cambiar_contrasena_exito.html'), name='password_change_done'),

    path('supervisor_estudiante_list/', views.supervisor_estudiante_list, name='supervisor_estudiante_list'),
    path('supervisor_aprobar_reporte/<int:pk>/', views.supervisor_aprobar_reporte, name='supervisor_aprobar_reporte'),
    
    path('evaluacion_aprobada_lista/', views.evaluacion_aprobada_lista, name='evaluacion_aprobada_lista'),
    
    path('generar_reporte/<int:pk>/', views.generar_reporte, name='generar_reporte'),
    path('reporte_aprobado/', views.reporte_aprobado, name='reporte_aprobado'),
    path('generar-pdf/<int:pk>/', generar_pdf, name='generar_pdf'),
    path('reporte_estudiante/', views.reporte_estudiante, name='reporte_estudiante'),
    
    
    path('usuarios-no-estudiantes/', listar_usuarios_no_estudiantes, name='listar_usuarios_no_estudiantes'),
    path('cambiar-rol/<int:pk>/', cambiar_rol, name='cambiar_rol'),
    
    path('listar_usuarios/', views.listar_usuarios, name='listar_usuarios'),
    
    path('eliminar-usuario/<int:pk>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('habilitar_usuario/<int:pk>/', views.habilitar_usuario, name='habilitar_usuario'),
    
]

unidad_educativa/urls.py
# unidad_educativa/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estudiantes.urls')),
]

estudiantes/forms.py
# estudiantes/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.forms import PasswordChangeForm


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return cleaned_data


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    rol = forms.ModelChoiceField(queryset=Rol.objects.all(), required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            perfil = Perfil.objects.create(user=user, rol=self.cleaned_data['rol'])
            perfil.save()
        return user
    

class TutorForm(forms.ModelForm):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    rol = forms.ModelChoiceField(queryset=Rol.objects.all(), required=True, label="Rol")

    class Meta:
        model = Tutor
        fields = ['nombre', 'profesion', 'experiencia', 'email', 'password', 'rol']


class RolForm(forms.Form):
    rol = forms.ModelChoiceField(queryset=Rol.objects.all(), label="Selecciona un rol")
    

class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Contraseña actual',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    new_password1 = forms.CharField(
        label='Nueva contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text=(
            'Tu contraseña no puede ser demasiado similar a tu otra información personal. '
            'Tu contraseña debe contener al menos 8 caracteres. '
            'Tu contraseña no puede ser una contraseña comúnmente usada. '
            'Tu contraseña no puede ser completamente numérica.'
        )
    )
    new_password2 = forms.CharField(
        label='Confirmación de nueva contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    
class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = ['nombre_empresa', 'direccion', 'telefono', 'correo_electronico', 'representante', 'supervisor', 'ruc']
        

templates/aprobar_estudiante.html
{% extends "bases/basehome.html" %}

{% block content %}
{% if request.session.rol == 'Administrador' %}
  <h2 class="col-sm-8 offset-sm-2">Aprobar Usuario</h2>
  <div class="col-sm-6 offset-sm-3">
    <p>¿Estás seguro de que quieres aprobar a {{ perfil.nombres |add:' ' |add:perfil.apellidos  }}?</p>
    <form method="POST" action="{% url 'aprobar_usuario' perfil.pk %}">
      {% csrf_token %}
      <p>Selecciona un Perfil para el usuario</p>
      <label for="id_rol">Selecciona un rol:</label>
      <select name="rol" id="id_rol" class="mb-3" required>
        <option value="">Selecciona una opción</option>
          {% for rol in form.fields.rol.queryset %}
              <option value="{{ rol.id }}">{{ rol.nombre }}</option>
          {% endfor %}
      </select>
      <br>

      <input type="hidden" name="nombre" value="{{ perfil.nombres |add:' ' |add:perfil.apellidos }}">
      <input type="hidden" name="estado" value="Aprobado">
      <button type="submit" class="btn btn-success mb-3">Aprobar</button>
    </form>
    <a href="{% url 'home' %}" class="btn btn-danger">Cancelar</a>
  </div>
{% endif %}
{% endblock %}

templates/cambiar_contrasena.html
{% extends 'bases/basehome.html' %}

{% block content %}
  <h2>Cambiar Contraseña</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Cambiar Contraseña</button>
  </form>
{% endblock %}

templates/cambiar_contrasena_exito.html
{% extends 'bases/basehome.html' %}

{% block content %}
  <h2>Contraseña Cambiada</h2>
  <p>Tu contraseña se ha cambiado correctamente.</p>
  <a href="{% url 'home' %}">Volver a la página principal</a>
{% endblock %}

templates/empresa_form.html
{% extends 'bases/basehome.html' %}

{% block content %}
    <h2>{% if object %}Editar{% else %}Agregar{% endif %} Empresa</h2>
    <form method="post">
        {% csrf_token %}
        <div class="col-sm-6 offset-sm-3">
            <div class="form-group row">
                <div class="col-sm-4 offset-sm-2 text-start">
                    <label for="nombre_empresa" class="form-label">Nombre de la Empresa</label>
                </div>
                <div class="col-md-4 ">
                    {{ form.nombre_empresa }}
                    {% if form.nombre_empresa.errors %}
                        <div class="text-danger">{{ form.nombre_empresa.errors }}</div>
                    {% endif %}
                </div>    
            </div>    

            <div class="form-group row">
                <div class="col-sm-4 offset-sm-2 text-start">
                    <label for="ruc" class="form-label">RUC</label>
                </div>
                <div class="col-md-4 ">
                    {{ form.ruc }}
                    {% if form.ruc.errors %}
                        <div class="text-danger">{{ form.ruc.errors }}</div>
                    {% endif %}
                </div>    
            </div>   

            <div class="form-group row">
                <div class="col-sm-4 offset-sm-2 text-start">
                    <label for="direccion" class="form-label">Dirección</label>
                </div>
                <div class="col-md-4 ">
                    {{ form.direccion }}
                    {% if form.direccion.errors %}
                        <div class="text-danger">{{ form.direccion.errors }}</div>
                    {% endif %}     
                </div>    
            </div>    

            <div class="form-group row">
                <div class="col-sm-4 offset-sm-2 text-start">
                    <label for="telefono" class="form-label">Teléfono</label>
                </div>
                <div class="col-md-4 ">
                    {{ form.telefono }}
                    {% if form.telefono.errors %}
                        <div class="text-danger">{{ form.telefono.errors }}</div>
                    {% endif %}
                </div>    
            </div>   

            <div class="form-group row">
                <div class="col-sm-4 offset-sm-2 text-start">
                    <label for="correo_electronico" class="form-label">Correo Electrónico</label>
                </div>
                <div class="col-md-4 ">
                    {{ form.correo_electronico }}
                    {% if form.correo_electronico.errors %}
                        <div class="text-danger">{{ form.correo_electronico.errors }}</div>
                    {% endif %}
                </div>    
            </div>   

            <div class="form-group row">
                <div class="col-sm-4 offset-sm-2 text-start">
                    <label for="representante" class="form-label">Representante</label>
                </div>
                <div class="col-md-4 ">
                    {{ form.representante }}
                    {% if form.representante.errors %}
                        <div class="text-danger">{{ form.representante.errors }}</div>
                    {% endif %}
                </div>    
            </div>   

            <div class="form-group row">
                <div class="col-sm-4 offset-sm-2 text-start">
                    <label for="supervisor" class="form-label">Supervisor</label>
                </div>
                <div class="col-md-4 ">
                    {{ form.supervisor }}
                    {% if form.supervisor.errors %}
                        <div class="text-danger">{{ form.supervisor.errors }}</div>
                    {% endif %}
                </div>    
            </div>  
            <p style="color:green;">Por favor colocar al supervisor segun formato "Nombre Apellido" </p>

        </div>   
         
        <button type="submit" class="btn btn-outline-success">Guardar</button>
    </form>
{% endblock %}

templates/empresa_list.html
{% extends 'bases/basehome.html' %}

{% block content %}
<h2>Empresas</h2>

<form method="GET" action="" class="col-sm-6 offset-sm-3">
    <div class="input-group mb-3">
        <input type="text" name="q" class="form-control" placeholder="Buscar empresa..." value="{{ request.GET.q }}">
        <button class="btn btn-outline-secondary" type="submit">Buscar</button>
    </div>
</form>

{% if request.session.estado_empresa == 'Aprobado' %}
    <h4>Ya está aprobada la Empresa</h4>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Nombre de la Empresa</th>
                        <th>Detalles</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empresa in object_list %}
                    <tr>
                        <td>{{ empresa.nombre_empresa }}</td>
                        <td><a class="btn btn-outline-primary" href="{% url 'empresa_detail' empresa.pk %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<a class="btn btn-outline-success mb-3" href="{% url 'empresa_create' %}">Agregar nueva empresa</a>
{% endif %}
<br>
<a class="btn btn-outline-primary" href="{% url 'home' %}">Regresar</a>
{% endblock %}

templates/ingreso.html
<!-- estudiantes/templates/ingreso.html -->
{% extends "bases/base.html" %}

{% block content %}
<h2 class="col-sm-8 offset-sm-2">Ingreso</h2>

<div class="container col-sm-6 mb-3">
    {% if messages %}
        <div>
            {% for message in messages %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>    

<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <div class="form-group col-sm-4 offset-sm-4 mb-3">
        <label for="username">Usuario</label>
        <input type="text" class="form-control" id="username" name="username" required>
        <p style="color:green"> El usuario va en minusculas y separado por "_" </p>
    </div>
    <div class="form-group col-sm-4 offset-sm-4  mb-3">
        <label for="password">Contraseña</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-outline-primary">Ingresar</button>
</form>

{% endblock %}


templates/manage_users.html
<!-- estudiantes/templates/estudiantes/sistema.html -->
{% extends 'bases/basehome.html' %}

{% block content %}
<div class="container">
    <h2>Gestionar Usuarios</h2>

    <form method="post">
        {% csrf_token %}
    
        <div class="mb-1">
            <label for="{{ form.username.id_for_label }}" class="form-label">Nombre de Usuario:</label>
            {{ form.username }}
        </div>

        <div class="mb-1">
            <label for="{{ form.email.id_for_label }}" class="form-label">Correo Electrónico:</label>
            {{ form.email }}
        </div>

        <div class="mb-1">
            <label for="{{ form.password.id_for_label }}" class="form-label">Contraseña:</label>
            {{ form.password }}
        </div>

        <div class="mb-1">
            <label for="{{ form.rol.id_for_label }}" class="form-label">Rol:</label>
            {{ form.rol }}
        </div>

        <button type="submit" class="btn btn-primary">Crear Usuario</button>
    </form>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>    

{% endblock %}

templates/preguntas_respuestas.html
<!-- estudiantes/templates/estudiantes/varios.html -->
{% extends 'bases/basehome.html' %}

{% block content %}

<h2>Revisar respuestas del Formulario</h2>
    <div>
        <p><strong>{{ pregunta1 }}</strong></p><p> {{ respuesta1 }}</p>
        <p><strong>{{ pregunta2 }}</strong></p><p> {{ respuesta2 }}</p>
        <p><strong>{{ pregunta3 }}</strong></p><p> {{ respuesta3 }}</p>
        <p><strong>{{ pregunta4 }}</strong></p><p> {{ respuesta4 }}</p>
        <p><strong>{{ pregunta5 }}</strong></p><p> {{ respuesta5 }}</p>
        <p><strong>{{ pregunta6 }}</strong></p><p> {{ respuesta6 }}</p>
        <p><strong>{{ pregunta7 }}</strong></p><p> {{ respuesta7 }}</p>
        <p><strong>{{ pregunta8 }}</strong></p><p> {{ respuesta8 }}</p>
        <p><strong>{{ pregunta9 }}</strong></p><p> {{ respuesta9 }}</p>
        <p><strong>{{ pregunta10 }}</strong></p><p> {{ respuesta10 }}</p>
        <p><strong>{{ pregunta11 }}</strong></p><p> {{ respuesta11 }}</p>
        <p><strong>{{ pregunta12 }}</strong></p><p> {{ respuesta12 }}</p>
        <p><strong>{{ pregunta13 }}</strong></p><p> {{ respuesta13 }}</p>
        <p><strong>{{ pregunta14 }}</strong></p><p> {{ respuesta14 }}</p>
        <p><strong>{{ pregunta15 }}</strong></p><p> {{ respuesta15 }}</p>
        <p><strong>{{ pregunta16 }}</strong></p><p> {{ respuesta16 }}</p>
        <p><strong>{{ pregunta17 }}</strong></p><p> {{ respuesta17 }}</p>
        <p><strong>{{ pregunta18 }}</strong></p><p> {{ respuesta18 }}</p>
        <p><strong>{{ pregunta19 }}</strong></p><p> {{ respuesta19 }}</p>
        <p><strong>{{ pregunta20 }}</strong></p><p> {{ respuesta20 }}</p>
        <p><strong>{{ pregunta21 }}</strong></p><p> {{ respuesta21 }}</p>
        <p><strong>{{ pregunta22 }}</strong></p><p> {{ respuesta22 }}</p>
        <p><strong>{{ pregunta23 }}</strong></p><p> {{ respuesta23 }}</p>
        <p><strong>{{ pregunta24 }}</strong></p><p> {{ respuesta24 }}</p>
        <p><strong>{{ pregunta25 }}</strong></p><p> {{ respuesta25 }}</p>
        <p><strong>{{ pregunta26 }}</strong></p><p> {{ respuesta26 }}</p>
        <p><strong>{{ pregunta27 }}</strong></p><p> {{ respuesta27 }}</p>
    </div>
    {% if request.session.estado_ia != 'Aprobado'%}
      <div class="form-group mt-3">
        <a href="{% url 'analisis_ia' %}"  class="btn btn-outline-success mb-3">Enviar respuestas a la IA</a>
      </div>
      {% endif%}
    <div class="form-group mt-3">
      <a href='{% url 'test' %}' class="btn btn-outline-primary mb-3">Regresar</a>
    </div>

{% endblock %}

templates/reportePDF.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@700&display=swap" rel="stylesheet">
    <title>UNIDAD EDUCATIVA ENRIQUE GIL GILBERT</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .container {
            width: 100%;
            margin: 0 auto;
        }

        .titulo-text {
            font-weight: bold;
        }

        .form-control {
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 15px;
        }

        .section {
            margin-bottom: 30px;
        }

        .section-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .section-content {
            font-size: 14px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .row {
            display: flex;
            justify-content: space-between;
        }

        .col-sm-6 {
            width: 48%;
        }

        img {
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
<body>

    <div class="container text-center">
        <img src="{% static 'img/logo.png' %}" width="10%" alt="Logo">
        <h6 class="titulo-text">UNIDAD EDUCATIVA</h6>
        <h4 class="titulo-text">ENRIQUE GIL GILBERT</h4>

        <h2>Reporte Final</h2>
        <h6 class="text-success mb-5"><strong>Reporte Generado en :</strong> {{ reporte.fecha_generacion|date:"d/m/Y" }}</h6>

        <table>
            <tr>
                <td width="50%">
                    <div class="section">
                        <div class="section-title"><h4>Datos del Estudiante</h4></div>
                        <div class="section-content">
                            <p class="form-control"><strong>Nombre del Estudiante:<br></strong>{{ perfil.nombres }} {{ perfil.apellidos }}</p>
                            <p class="form-control"><strong>Especialización:<br></strong>{{ perfil.especializacion }}</p>
                        </div>
                    </div>
                </td>
                <td width="50%">
                    <div class="section">
                        <div class="section-title"><h4>Datos de la Empresa</h4></div>
                        <div class="section-content">
                            <p class="form-control"><strong>Nombre de la Empresa:<br></strong>{{ perfil.empresa_nombre }}</p>
                            <p class="form-control"><strong>Dirección:<br></strong>{{ perfil.empresa_nombre.direccion }}</p>
                            <p class="form-control"><strong>Correo Electrónico:<br></strong>{{ perfil.empresa_nombre.correo_electronico }}</p>
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="section">
            <div class="section-title"><h4>Período de Prácticas</h4></div>
            <div class="section-content">
                <p class="form-control"><strong>Fecha de Inicio:<br></strong>{{ perfil.reporte_fecha_inicio }}</p>
                <p class="form-control"><strong>Fecha de Finalización:<br></strong>{{ perfil.reporte_fecha_final }}</p>
            </div>
        </div>

        <div class="section">
            <div class="section-title"><h4>Horas Realizadas</h4></div>
            <div class="section-content">
                <h4 class="text-success">160 horas</h4>
            </div>
        </div>

        <div class="section">
            <div class="section-title"><h4>Conclusiones</h4></div>
            <div class="section-content">
                <p>{{ reporte.conclusiones }}</p>
            </div>
        </div>

        <div class="section">
            <div class="section-title"><h4>Observaciones</h4></div>
            <div class="section-content">
                <p>{{ reporte.observaciones }}</p>
            </div>
        </div>

        <div class="form-group row mb-3">
            <div class="col-sm-6">
                <img src="{{ request.build_absolute_uri }}{% static 'img/SelloColegio.png' %}" alt="Sello" width="100px">
                <img src="{{ request.build_absolute_uri }}{% static 'img/FirmaRectora.png' %}" class="card-img-top" alt="Firma Rectora">
                <div class="card-body">
                    <p class="card-text">Msgt. {{ reporte.rector | upper }}</p>
                    <p class="card-text"><strong>Rector(a) de la Unidad Educativa Fiscal ‘ENRIQUE GIL GILBERT’</strong></p>
                </div>
            </div>
            <div class="col-sm-6">
                <img src="{{ request.build_absolute_uri }}{% static 'img/sellogenerico.jpg' %}" alt="Firma" width="100px">
                <div class="card-body">
                    <p class="card-text">{{ perfil.empresa_nombre }}</p>
                    <p class="card-text"><strong>Entidad</strong></p>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

templates/tutor_confirm_delete.html
{% extends 'bases/basehome.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-6 offset-3">
            <h2>Eliminar Tutor</h2>
            <p>¿Estás seguro de que deseas eliminar a "{{ tutor.nombre }}"?</p>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-outline-danger" type="submit">Confirmar</button>
            </form>
                <br>
            </div>

            <a href="{% url 'tutor_list' %}" class="btn btn-outline-primary col-sm-2 offset-sm-5">Regresar</a>
        </div>
    </div>
</div>

{% endblock %}